"""initial schema

Revision ID: 3c6a917f5bc4
Revises: 
Create Date: 2026-06-06 17:51:10.543252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6a917f5bc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('jugadores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('numero_camiseta', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.String(length=36), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipo_id', 'numero_camiseta', name='uq_equipo_numero')
    )
    op.create_table('partidos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('equipo_local_id', sa.String(length=36), nullable=False),
    sa.Column('equipo_visitante_id', sa.String(length=36), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('goles_local', sa.Integer(), nullable=False),
    sa.Column('goles_visitante', sa.Integer(), nullable=False),
    sa.Column('fase', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('equipo_local_id != equipo_visitante_id', name='ck_equipos_diferentes'),
    sa.ForeignKeyConstraint(['equipo_local_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['equipo_visitante_id'], ['equipos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('partido_id', sa.String(length=36), nullable=False),
    sa.Column('jugador_id', sa.String(length=36), nullable=True),
    sa.Column('equipo_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('minuto', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugadores.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos')
    op.drop_table('partidos')
    op.drop_table('jugadores')
    op.drop_table('equipos')
    # ### end Alembic commands ###
