"""add categoria model

Revision ID: d2edbfc277b3
Revises: 3c6a917f5bc4
Create Date: 2026-06-06 19:05:33.722725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2edbfc277b3'
down_revision = '3c6a917f5bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_equipos_categoria_id', 'categorias', ['categoria_id'], ['id'])

    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_partidos_categoria_id', 'categorias', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partidos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_partidos_categoria_id', type_='foreignkey')
        batch_op.drop_column('categoria_id')

    with op.batch_alter_table('equipos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_equipos_categoria_id', type_='foreignkey')
        batch_op.drop_column('categoria_id')

    op.drop_table('categorias')
    # ### end Alembic commands ###
